version: '3.9'

services:
  frontend:
    build: ./todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./todo-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_list?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '0'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '0'
      MYSQL_DATABASE: todo_list
      MYSQL_USER: root
      MYSQL_PASSWORD: '0'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
