services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - nginx-cache:/var/cache/nginx
    environment:
      - CURRENT_ENV=blue
    command: /bin/bash -c "envsubst '\$CURRENT_ENV' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf.tmp && mv /etc/nginx/nginx.conf.tmp /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend-blue
      - backend-blue

  frontend-blue:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    image: thanh2k4/todo_list-frontend:blue
    user: root
    expose:
      - "80"

  backend-blue:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: thanh2k4/todo_list-backend:blue
    expose:
      - "8080"
    environment:
      DB_URL: ${DB_URL:-mysql://db:3306/todo_list}
      DB_USERNAME: ${MYSQL_USER:-root}
      DB_PASSWORD: ${MYSQL_PASSWORD:-0}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-0}
      MYSQL_DATABASE: todo_list
    volumes:
      - mysql-data:/var/lib/mysql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro

volumes:
  mysql-data:
  nginx-cache:
