version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-blue
      - frontend-green
      - backend-blue
      - backend-green

  frontend-blue:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    image: thanh2k4/todo_list-frontend:blue
    expose:
      - "80"

  frontend-green:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    image: thanh2k4/todo_list-frontend:green
    expose:
      - "80"

  backend-blue:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: thanh2k4/todo_list-backend:blue
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_list?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '0'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  backend-green:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: thanh2k4/todo_list-backend:green
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_list?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '0'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '0'
      MYSQL_DATABASE: todo_list
      MYSQL_USER: root
      MYSQL_PASSWORD: '0'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


