version: "3.8"
services:
  frontend:
    build:
      context: ./todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./todo-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/todo_list?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: '0'
      MYSQL_DATABASE: todo_list
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
