DB_URL : mysql://localhost:3306/todo_list
DB_USERNAME : root
DB_PASSWORD : 0
CORS_ORIGIN : http://localhost:3000
spring:
  application:
    name: todo-backend

  datasource:
    url: jdbc:${DB_URL}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


