name: Deploy

on:
  workflow_run:
    workflows: ["build-and-test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Deploy to Docker
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t todo-app-backend:latest ./todo-backend
        docker build -t todo-app-frontend:latest ./todo-frontend
        docker tag todo-app-backend:latest ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:latest
        docker tag todo-app-frontend:latest ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:latest


    - name: Deploy Backend to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "todo-backend-thanh2k4"
        heroku_email: "nvthanh12102004@gmail.com"
        appdir: "todo-backend"
      env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
